// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint:
        "https://tj2rfcdbfrcx3emxk5plwny35u.appsync-api.ap-southeast-2.amazonaws.com/graphql",
      region: "ap-southeast-2",
      defaultAuthMode: "apiKey",
      apiKey: "da2-aprhk3hrejhp3o22rdxt6qlbdm",
    },
  },
};

export default config;
